const BaseText = {
    HomeScreen: 'This is the home screen',
    Next: 'NEXT',
    Skip: 'SKIP',
    ShoppingHome: 'SHOPPING FROM HOME',
    IntroDetails: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer maximus accumsan erat id facilisis.',
    Sign_Up: 'SIGN UP',
    SignIn: 'Sign in',
    SignUP: 'Sign up',
    NEXT: 'Next',
    Sign_IN: 'SIGN IN',
    GET_OTP: 'GET OTP',
    SignInHeaderTitle1: 'Please Enter your Name.',
    SignInHeaderTitle2: 'And getRegistered in few seconds',
    Youremail: 'Your email',
    Forgotpassword: 'Forgot password?',
    ForgotpasswordText: 'Forgot password',
    ContinueGoogle: 'CONTINUE WITH GOOGLE',
    ContinueFacebook: 'CONTINUE WITH FACEBOOK',
    OrSign: 'Or Sign in with social media',
    Yourpassword: 'Your password',
    Yourname: 'Your name',
    Confirmpassword: 'Confirm password',
    Enteryouremail: 'Enter your email',
    Youremailaddress: 'Your email address',
    Codesendemail: 'Code was send your email',
    Codeexpireon: 'This code will expire on ',
    SaveEmailAdd: 'SAVE EMAIL ADDRESS',
    ResendLink: 'RESEND LINK',
    SavePhoneNum: 'SAVE PHONE NUMBER',
    Enteryourphone: 'Enter your phone',
    EnterphoneNum: 'Enter phone number',
    SetNewpassword: 'Set a new password',
    EnterNewpassword: 'Enter new password',
    ConfirmNewpassword: 'Confirm new password',
    SavePassword: 'SAVE PASSWORD',
    ResendCode: 'RESEND CODE',
    VerifyCode: 'VERIFY CODE',
    VerifyOTP: 'VERIFY OTP',
    Search: 'Search',
    Category: 'Category',
    SaleDiscount: 'Sale Discount',
    Popular: 'Popular',
    Charge: 'Charge',
    Transfer: 'Transfer',
    Credit: 'Credit',
    PayLater: 'Pay Later',
    Settings: 'Settings',
    Pay: 'pay',
    TopUp: 'Top Up',
    ConfirmOTP: 'Confirm OTP',
    More: 'More',
    Filters: 'Filters',
    MyCart: 'My Cart',
    CheckOut: 'CHECK OUT',
    Color: 'Color : ',
    Size: 'Size : ',
    SubTotal: 'Sub Total :',
    smallSubTotal: 'Subtotal',
    Payment: 'Payment',
    ShippingAddress: 'Shipping Address',
    Edit: 'Edit',
    DeliveryService: 'Delivery Service',
    ExpressDelivery: 'Express Delivery',
    AddDescription: 'Add Description',
    MyPay: 'My Pay',
    SubTpro: 'Subtotals for products',
    SubTship: 'Subtotals for shipping',
    TotalPayment: 'Total Payment',
    SendDropshipper: 'Send As a Dropshipper',
    Total: 'Total',
    BuyNow: 'BUY NOW',
    EnterPaypin: 'Enter the My Pay pin',
    Forgotpin: 'Forgot pin?',
    Buy: 'Buy',
    ContinueShopping: 'CONTINUE SHOPPING',
    Success: 'SUCCESS',
    SucessShoppingInfo: 'Thank you for purchasing. Your order will be shipped 2 - 4 working days.',
    PaymentMethod: 'Payment Method',
    ConfirmOTPDescription: 'Confirm OTP via phone number',
    ConfirmcodeInfo: 'OTP was sent via sms to your phone number + 1424-XXXX-XX67, enter the code !',
    TopUpTitle: 'Top Up',
    NominalText: 'Nominal input',
    AddDebitCard: 'Add a debit card',
    AddDebitCardDes: 'Can this balance directly from here',
    Continue: 'CONTINUE',
    $10: '$10',
    $50: '$50',
    $100: '$100',
    $200: '$200',
    AccountName: 'Account name',
    Bank: 'Bank',
    AccountNumber: 'Account number',
    Expire: 'Expire',
    SecurityCode: 'Security code',
    addDebitBtn: 'ADD DEBIT CARD',
    Pay: 'Pay',
    Disc: 'Disc',
    S: 'S',
    M: 'M',
    L: 'L',
    XL: 'XL',
    Choosecolor: 'Choose a color :',
    SelectQty: 'Select Quality :',
    Description: 'Description',
    AddtoCart: 'ADD TO CART',
    ToBankAccount: 'To a Bank Account',
    Transferaccount: 'Transfer to a new account',
    Choosedestinationbank: 'Choose your destination bank',
    ListAccount: 'List Account',
    NotAvailable: 'Not Available',
    ScanQRCode: 'Scan the code using your camera',
    PaySend: 'Pay And Send',
    ToPhoneNumber: 'To a Phone Number',
    UseCode: 'Use Code',
    Notification: 'Notification',
    EmptyNotificationTitle: 'No message notification found! We will let you know if there is any notification for you.',
    ReturnHome: 'RETURN TO HOME',
    HappyDay: 'Happy Day.'


}
export default BaseText;