const Images = {
    orangelogo: require('assets/CommonIcon/orangelogo.png'),
    //App Intro 
    exoressDelivery: require('assets/IntroIcon/exoressDelivery.png'),
    produk: require('assets/IntroIcon/produk.png'),
    shoppingHome: require('assets/IntroIcon/shoppingHome.png'),

    //Comman
    previousArrowWhite: require('assets/CommonIcon/previousArrowWhite.png'),
    hidePassword: require('assets/CommonIcon/hidePassword.png'),
    facebook: require('assets/CommonIcon/facebook.png'),
    google: require('assets/CommonIcon/google.png'),
    search: require('assets/CommonIcon/search.png'),
    shoppingCart: require('assets/CommonIcon/shoppingCart.png'),
    fillter: require('assets/CommonIcon/fillter.png'),
    ratingIcon: require('assets/CommonIcon/ratingIcon.png'),
    cartRound: require('assets/CommonIcon/cartRound.png'),
    previousArrowRound: require('assets/CommonIcon/previousArrowRound.png'),
    menu: require('assets/CommonIcon/menu.png'),
    slideUp: require('assets/CommonIcon/slideUp.png'),
    bike1: require('assets/CommonIcon/bike1.png'),
    bike: require('assets/CommonIcon/bike.jpeg'),
    takePicture: require('assets/CommonIcon/takePicture.png'),
    emptyNotification: require('assets/CommonIcon/emptyNotification.png'),
    notificationDot: require('assets/CommonIcon/notificationDot.png'),

    // Tab
    activeHome: require('assets/TabIcon/activeHome.png'),
    deActiveHome: require('assets/TabIcon/deActiveHome.png'),
    activeNotification: require('assets/TabIcon/activeNotification.png'),
    deActiveNotification: require('assets/TabIcon/deActiveNotification.png'),
    activeProfile: require('assets/TabIcon/activeProfile.png'),
    deActiveProfile: require('assets/TabIcon/deActiveProfile.png'),
    tabUserprofile: require('assets/TabIcon/tabUserprofile.png'),

    //Dashboard
    women: require('assets/Dashboard/women.png'),
    fooddrink: require('assets/Dashboard/fooddrink.png'),
    child: require('assets/Dashboard/child.png'),
    electrinoc: require('assets/Dashboard/electrinoc.png'),
    furniture: require('assets/Dashboard/furniture.png'),
    hobby: require('assets/Dashboard/hobby.png'),
    kitchentools: require('assets/Dashboard/kitchentools.png'),
    men: require('assets/Dashboard/men.png'),
    more: require('assets/Dashboard/more.png'),
    pay: require('assets/Dashboard/pay.png'),
    purse: require('assets/Dashboard/purse.png'),
    topUp: require('assets/Dashboard/topUp.png'),
    discountCard: require('assets/Dashboard/discountCard.png'),
    lovewhite: require('assets/Dashboard/lovewhite.png'),
    lovered: require('assets/Dashboard/lovered.png'),
    popularCart: require('assets/Dashboard/popularCart.png'),
    tpCredit: require('assets/Dashboard/tpCredit.png'),
    tpCharge: require('assets/Dashboard/tpCharge.png'),
    tpPaylater: require('assets/Dashboard/tpPaylater.png'),
    tpSetting: require('assets/Dashboard/tpSetting.png'),
    tpTransfer: require('assets/Dashboard/tpTransfer.png'),

    //Profile
    order: require('assets/ProfileIcon/order.png'),
    payment: require('assets/ProfileIcon/payment.png'),
    address: require('assets/ProfileIcon/address.png'),
    favourites: require('assets/ProfileIcon/favourites.png'),
    account: require('assets/ProfileIcon/account.png'),
    profileCover: require('assets/ProfileIcon/profileCover.png'),

    //Check Box
    checkbox: require('assets/CheckOut/checkbox.png'),
    subscrtion: require('assets/CheckOut/subscrtion.png'),
    addition: require('assets/CheckOut/addition.png'),
    deleteGray: require('assets/CheckOut/deleteGray.png'),
    deleteWhite: require('assets/CheckOut/deleteWhite.png'),
    checklis: require('assets/CheckOut/checklis.png'),
    puresPink: require('assets/CheckOut/puresPink.png'),
    nextRound: require('assets/CheckOut/nextRound.png'),
    success: require('assets/CheckOut/success.png'),
    bank: require('assets/CheckOut/bank.png'),
    infoIcon: require('assets/CheckOut/infoIcon.png'),
    telephone: require('assets/CheckOut/telephone.png'),
    barCode: require('assets/CheckOut/barCode.png'),

    //Top Up
    coin10: require('assets/TopUp/Coin10.png'),
    coin50: require('assets/TopUp/Coin50.png'),
    coin100: require('assets/TopUp/Coin100.png'),
    coin200: require('assets/TopUp/Coin200.png'),
    pressDownIcon: require('assets/TopUp/pressDownIcon.png'),

    //Static Imges
    sdheels: require('assets/StaticImges/sdheels.png'),
    sdChair: require('assets/StaticImges/sdChair.png'),
    sdPan: require('assets/StaticImges/sdPan.png'),
    sdShoes: require('assets/StaticImges/sdShoes.png'),
    sdjacket: require('assets/StaticImges/sdjacket.png'),
    popbeg: require('assets/StaticImges/popbeg.png'),
    pophanky: require('assets/StaticImges/pophanky.png'),
    serOr: require('assets/StaticImges/serOr.png'),
    serFlo: require('assets/StaticImges/serFlo.png'),
    serEme: require('assets/StaticImges/serEme.png'),
    serPeach: require('assets/StaticImges/serPeach.png'),
    serpuf: require('assets/StaticImges/serpuf.png'),
    serSaphi: require('assets/StaticImges/serSaphi.png'),
    chekLeviJens: require('assets/StaticImges/chekLeviJens.png'),
    checkMilano: require('assets/StaticImges/checkMilano.png'),
    catPillow: require('assets/StaticImges/catPillow.png'),
    catbed: require('assets/StaticImges/catbed.png'),
    catchair: require('assets/StaticImges/catchair.png'),
    catDraw: require('assets/StaticImges/catDraw.png'),
    catPlant: require('assets/StaticImges/catPlant.png'),
    catsofa: require('assets/StaticImges/catsofa.png'),
    catpsprisofa: require('assets/StaticImges/catpsprisofa.png'),
    catpAnn: require('assets/StaticImges/catpAnn.png'),
    catpGchair: require('assets/StaticImges/catpGchair.png'),
    ptcol: require('assets/StaticImges/ptcol.png'),
    ptann: require('assets/StaticImges/ptann.png'),
    ptinc: require('assets/StaticImges/ptinc.png'),
    ptmil: require('assets/StaticImges/ptmil.png'),
    ptopu: require('assets/StaticImges/ptopu.png'),
    ptVio: require('assets/StaticImges/ptVio.png'),

    // shop Type Icons
    shopGroceries: require('assets/ShopIcon/confectionary.png'),
}
export default Images;